### ISSUE TITLE
split `runtests.jl` suite into multiple files

### ISSUE THREAD

**Issue by SimonEnsemble** [SimonEnsemble/PorousMaterials.jl#25]
(@ahyork plz for when summer starts!)
current the `runtests.jl` is a mess:
* lack of comments (some are my fault but we should try to justify the tests)
* each test suite should be independent and moved to a different file e.g. `crystal_tests.jl`
* there are many dependences where e.g a framework is defined way up top, not used for a while, but then used again at the bottom. partitioning the tests into modules for each test suite will help fix this. but each test should be as independent and modular as possible.
* how to get `Pkg.test("PorousMaterials")` to run the tests instead of `cd`'ing into the test directory and running the manually? i.e. we would like the tests to interface with the julia package manager eventually
* GCMC tests should still be separate since these take super long to run.

**Comment by SimonEnsemble** [comment]
nevermind; Travis CI wants all tests in one file.
Still, would be great if each test suite were independent of the others! so e.g. `framework` from one test is not used in a test down the road.

**Comment by ahyork** [comment]
This is resolved with the latest pull request improving speed. Each test set is in its own file now. Because they are each inside their own module they are tested in different global scopes, stopping the issue of one variable being used multiple times in different tests when they are all included in runtests.jl.
